#pragma once

#define CONFIG_LV_DISPLAY_ORIENTATION 2
#define CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9341 1
#define CONFIG_LV_TFT_DISPLAY_PROTOCOL_SPI 1
#define CONFIG_LV_TFT_DISPLAY_SPI_HSPI 1

#define CORE2
//#define ITEM2
#ifdef CORE2
    #define CONFIG_LV_DISPLAY_USE_SPI_MISO 
    #define CONFIG_LV_DISP_PIN_DC 15
    #define CONFIG_LV_DISP_SPI_MOSI 23
    #define CONFIG_LV_DISP_SPI_MISO 38
    #define CONFIG_LV_DISP_SPI_CLK 18
    #define CONFIG_LV_DISPLAY_USE_SPI_CS 1
    #define CONFIG_LV_DISP_SPI_CS 5
    #define CONFIG_LV_ENABLE_BACKLIGHT_CONTROL 0
#else 
    #define CONFIG_LV_PREDEFINED_DISPLAY_M5STACK 1
    #define CONFIG_DISPLAY_ORIENTATION_LANDSCAPE 1
    #define CONFIG_LV_DISPLAY_ORIENTATION 2
    #define CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_SIO 1
    #define CONFIG_LV_TFT_DISPLAY_SPI_HALF_DUPLEX 1
    #define CONFIG_LV_TFT_CUSTOM_SPI_CLK_DIVIDER 2
    #define CONFIG_LV_DISP_SPI_MOSI 23
    #define CONFIG_LV_DISP_SPI_CLK 18
    #define CONFIG_LV_DISPLAY_USE_SPI_CS 1
    #define CONFIG_LV_DISP_SPI_CS 14
    #define CONFIG_LV_DISPLAY_USE_DC 1
    #define CONFIG_LV_DISP_PIN_DC 27
    #define CONFIG_LV_DISP_PIN_RST 33
    #define CONFIG_LV_DISP_PIN_BUSY 35
    #define CONFIG_LV_ENABLE_BACKLIGHT_CONTROL 1
    #define CONFIG_LV_BACKLIGHT_ACTIVE_LVL 1
    #define CONFIG_LV_DISP_PIN_BCKL 32
    #define CONFIG_LV_DISP_PIN_SDA 5
    #define CONFIG_LV_DISP_PIN_SCL 4
    #define CONFIG_LV_TOUCH_CONTROLLER 0
    #define CONFIG_LV_TOUCH_CONTROLLER_NONE 1
#endif 
    #define CONFIG_LV_INVERT_COLORS 1
    #define CONFIG_LV_DISP_SPI_INPUT_DELAY_NS 0
//#define SPI_TFT_CLOCK_SPEED_HZ (16 * 1000 * 1000)

#define DISP_BUF_SIZE (320 * 240)/10

//#define SPI_BUS_MAX_TRANSFER_SZ (DISP_BUF_SIZE*16)

#define SPI_TFT_SPI_MODE (0)

#define CONFIG_I2C_SDA 21
#define CONFIG_I2C_SCL 22
#define TOUCH_I2C_SPEED_HZ 400000
